dry_run: False
simulate_responses: True
simulate_participants: True
N_simul_batch_1: 256
N_simul_batch_2: 0

storage:
  experiment: jack_testing_1_repeat
  local: True
  cloud: False

dqn:
  criterion: MSELoss
  optimizer: SGD
  optimizer_kw:
    momentum: 0.9
  train_lr: .01
  warmup_lr: .05
  warmup_iters: 50000
  num_samples: 50000
  sync_steps: 2
  epsilon: .2
  epsilon_decay: .9
  gamma: .8

  model:
    input_shape: 8
    hidden_shape: 128
    output_shape: 1596
    hidden_layers: 1
    hidden_activation: LeakyReLU
    hidden_activation_kw:
      negative_slope: 0.2

  memory:
    capacity: 512
    batch_size: 256

  convergence:
    training: 50
    warmup: 50
    min_loss: .005
