dry_run: False
simulate_responses: True
simulate_participants: True
N_simul_batch_1: 256
N_simul_batch_2: 0

storage:
  experiment: jack_testing_10
  local: True
  cloud: True

dqn:
  criterion: MSELoss
  optimizer: SGD
  optimizer_kw:
    momentum: 0.9
    weight_decay: 1e-4
  train_lr: .005
  warmup_lr: .01
  warmup_iters: 5000
  num_samples: 5000
  sync_steps: 2
  epsilon: .8
  epsilon_decay: .9
  gamma: .7

  model:
    input_shape: 8
    hidden_shape: 128
    output_shape: 1596
    hidden_layers: 1
    hidden_activation: LeakyReLU
    hidden_activation_kw:
      negative_slope: 0.2

  memory:
    capacity: 512
    batch_size: 256

  convergence:
    training: 50
    warmup: 100
    min_loss: .01
