dry_run: True
simulate_responses: True
simulate_participants: True
N_simul_batch_1: 64
N_simul_batch_2: 16

storage:
  experiment: sample
  shared_prefix: sample
  local: True
  cloud: False

cluster:
  n_clusters: 4

dqn:
  criterion: MSELoss
  optimizer: SGD
  optimizer_kw:
    momentum: 0.9
  train_lr: .01
  warmup_lr: .05
  warmup_iters: 400
  num_samples: 150
  sync_steps: 2
  epsilon: .2
  epsilon_decay: .9
  gamma: .8

  model:
    input_shape: 8
    hidden_shape: 128
    output_shape: 1596
    hidden_layers: 1
    hidden_activation: LeakyReLU
    hidden_activation_kw:
      negative_slope: 0.2

  memory:
    capacity: 128
    batch_size: 64

  convergence:
    training:
      reps_min_loss: 10
      min_loss: .05
      reps_min_delta: 50
      min_delta: .001
    warmup:
      reps_min_loss: 10
      min_loss: .05
      reps_min_delta: 50
      min_delta: .001
